### ISSUE TITLE
The problem of inappropriate numpy versions

### ISSUE THREAD

**Issue by TheWindWillNotStop** [KumaTea/pytorch-aarch64#9]
Hi Kuma, Since I have to use both tensorflow and torch in my project, the torch wheel you provided requires numpy >= 1.20.0, but some interfaces in tensorflow only work when numpy <= 1.20.0, I have no way to solve this problem, do you have a better idea? Thanks

**Comment by KumaTea** [comment]
Hi.

According to [this answer](https://stackoverflow.com/a/6572017/10714490), there is currently no perfect solution for this situation. `venv` or `conda` won't help.

---

If there is a version that is accepted by both `torch` and `tensorflow`, in your env `numpy==1.20.0`, it's great to just install that.

Otherwise, I'll recommend installing a newer version, and ignore the dep warnings.
Or maybe you could compile from source with your specific version of `numpy` to avoid potential errors.

**Comment by TheWindWillNotStop** [comment]
I found the same situation as mine in tensorflow issues, I think it's due to the ARM architecture that I have to upgrade numpy to version 1.20, but tensorflow still has problems with numpy support, the only way I can do it now is to decouple and rewrite the project. Thanks for your time
